name = 'eggtart-script'
main = "src/worker.ts"
compatibility_date = "2026-04-21"

[assets]
directory = "./admin/dist"
binding = "ASSETS"
run_worker_first = true

[[kv_namespaces]]
binding = "EGGTART_CONFIG_KV"
id = "e2e91831e3d1498dbb77ae7e315d6766"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[env.EGGTART_EMAIL]
[env.EGGTART_PASSWORD]
[env.ADMIN_SESSION_SECRET]
